- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: change UID user nginx
  user:
    name: nginx
    uid: 1121

- name: change gid user nginx
  group:
    name: nginx
    gid: 1120

- name: enable service nginx and ensure it is not masked
  systemd:
    name: nginx
    enabled: yes
    masked: no
